 options:
   logging: CLOUD_LOGGING_ONLY
 substitutions:
   _REGION: "me-west1"
   _PROJECT_ID: "sandbox-lz-rachelge"
 steps:
  - name: "gcr.io/cloud-builders/docker"
    dir: "client/my-app"
    args: ["build", "-t", "me-west1-docker.pkg.dev/sandbox-lz-rachelge/repo/frontend:latest", "."]


  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "me-west1-docker.pkg.dev/sandbox-lz-rachelge/repo/frontend:latest"]
  
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - run
      - deploy
      - frontend
      - --image=me-west1-docker.pkg.dev/${_PROJECT_ID}/repo/frontend:latest
      - --region=${_REGION}
      - --port=80
      - --platform=managed
      - --service-account=cloud-run-executor-server@${_PROJECT_ID}.iam.gserviceaccount.com