options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "me-west1"

steps:
  # ---------- FRONTEND ----------
  - name: "gcr.io/cloud-builders/docker"
    dir: "client/my-app"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/frontend:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/frontend:$SHORT_SHA"]

  # - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #   args:
  #     - gcloud
  #     - run
  #     - deploy
  #     - frontend
  #     - --image=gcr.io/$PROJECT_ID/frontend:$SHORT_SHA
  #     - --region=${_REGION}
  #     - --platform=managed
  #     - --quiet

  # ---------- BACKEND ----------
  - name: "gcr.io/cloud-builders/docker"
    dir: "server"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/backend:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend:$SHORT_SHA"]

  # - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #   args:
  #     - gcloud
  #     - run
  #     - deploy
  #     - backend
  #     - --image=gcr.io/$PROJECT_ID/backend:$SHORT_SHA
  #     - --region=${_REGION}
  #     - --platform=managed
  #     - --quiet
