version: '3.8'
services:
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 8000:8000
    volumes:
       - ./src:/src  
  client:
    container_name: client
    build:
      context: ./client/my-app
      # args:
      #   VITE_BACKEND_URL: http://localhost:8000
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    depends_on:
      - server




# version: '3'
# services:
#   server:
#     container_name: server
#     build:
#       context: ./server
#     ports:
#       - 8000:8000
#     volumes:
#        - ./src:/src
#   client:
#     container_name: client
#     build:
#       context: ./client/my-app
#       args:
#         VITE_BACKEND_URL: http://localhost:8000
#     ports:
#       - 5173:5173
#     depends_on:
#       - server
