options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # שלב 1: שליפת כתובת ה־Backend ויצירת קובץ env.js
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-backend-url'
    entrypoint: 'bash'
    env:
      - 'REGION=me-west1'
      - 'PROJECT_ID=sandbox-lz-rachelge'
    args:
      - -c
      - |
        BACKEND_URL=$(gcloud run services describe cloud-run-server --platform=managed --region=$REGION --format='value(status.url)')
        echo "window.VITE_BACKEND_URL = \"$BACKEND_URL\";" > client/my-app/public/env.js

  # שלב 2: בניית דוקר לאפליקציית ה-Frontend
  - name: "gcr.io/cloud-builders/docker"
    dir: "client/my-app"
    env:
      - 'PROJECT_ID=sandbox-lz-rachelge'
    args:
      - build
      - -t
      - "gcr.io/$PROJECT_ID/frontend:latest"
      - "."

  # שלב 3: דחיפת התמונה ל־Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    env:
      - 'PROJECT_ID=sandbox-lz-rachelge'
    args:
      - push
      - "gcr.io/$PROJECT_ID/frontend:latest"

images:
  - "gcr.io/sandbox-lz-rachelge/frontend:latest"
