options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "me-west1"
  _PROJECT_ID: "sandbox-lz-rachelge"
  _BACKEND_URL: unused
  

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-backend-url'
    entrypoint: 'bash'
    args:
      - -c
      - |
        BACKEND_URL=$(gcloud run services describe cloud-run-backend --platform=managed --region=me-west1 --format="value(status.url)")
        echo "window.VITE_BACKEND_URL = \"$BACKEND_URL\";" > client/my-app/public/env.js

  
  - name: "gcr.io/cloud-builders/docker"
    dir: "client/my-app"
    args: ["build", "-t", "me-west1-docker.pkg.dev/${_PROJECT_ID}/repo/frontend:latest", "."]

 
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "me-west1-docker.pkg.dev/${_PROJECT_ID}/repo/frontend:latest"]

 
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - run
      - deploy
      - cloud-run-frontend
      - --image=me-west1-docker.pkg.dev/${_PROJECT_ID}/repo/frontend:latest
      - --region=${_REGION}
      - --port=80
      - --platform=managed
      # - --service-account=${_SERVICE_ACCOUNT}


